name: Debug CI Issues

on:
  workflow_dispatch:
  push:
    branches: [ debug-ci ]

jobs:
  debug:
    name: Debug Environment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: System Information
      run: |
        echo "=== System Information ==="
        echo "OS: ${{ runner.os }}"
        echo "Python Version: ${{ matrix.python-version }}"
        python --version
        pip --version
        
    - name: Test Git Access
      run: |
        echo "=== Testing Git Access ==="
        git --version
        git ls-remote https://github.com/cloudQuant/empyrical.git HEAD || echo "GitHub access failed"
        
    - name: Test Pip Install
      run: |
        echo "=== Testing Pip Install ==="
        pip install --upgrade pip
        pip install numpy pandas matplotlib ipython
        
    - name: Test Empyrical Install
      run: |
        echo "=== Testing Empyrical Install ==="
        pip install git+https://github.com/cloudQuant/empyrical.git --verbose || echo "Empyrical install failed"
        
    - name: List Installed Packages
      if: always()
      run: |
        echo "=== Installed Packages ==="
        pip list
        
    - name: Check Import
      if: always()
      run: |
        echo "=== Testing Imports ==="
        python -c "import numpy; print(f'NumPy: {numpy.__version__}')"
        python -c "import pandas; print(f'Pandas: {pandas.__version__}')"
        python -c "import empyrical; print(f'Empyrical: {empyrical.__version__}')" || echo "Empyrical import failed"