name: Minimal Test

on:
  workflow_dispatch:
  push:
    branches: [ test-ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies in correct order
      run: |
        echo "=== Installing pip ==="
        python -m pip install --upgrade pip
        
        echo "=== Installing test dependencies ==="
        pip install pytest parameterized
        
        echo "=== Installing IPython ==="
        pip install ipython
        
        echo "=== Installing other dependencies ==="
        pip install matplotlib numpy pandas flask pytz scikit-learn scipy seaborn
        
        echo "=== Installing empyrical ==="
        pip install git+https://github.com/cloudQuant/empyrical.git
        
        echo "=== Installing pyfolio without deps ==="
        pip install -e . --no-deps
        
        echo "=== Verifying imports ==="
        python -c "import IPython; print(f'IPython {IPython.__version__}')"
        python -c "import parameterized; print('parameterized OK')"
        python -c "import pyfolio; print(f'pyfolio {pyfolio.__version__}')"
        
    - name: Run a simple test
      run: |
        pytest tests/test_utils.py -v